import { Prodotto } from '../tipi';

// 24 prodotti finti, tutti senza obbligo di ricetta (OTC/SOP) o parafarmacia,
// quattro per ogni categoria. piuCercato serve alla sezione "Più cercati".
const prodotti: Prodotto[] = [
  {
    id: 'p01',
    nome: 'Tachipirina 500 mg',
    marca: 'Angelini',
    formato: '20 compresse',
    descrizione:
      'Paracetamolo per abbassare la febbre e calmare il mal di testa e i dolori leggeri.',
    categoria: 'dolore-febbre',
    piuCercato: true,
    aspetto: {
      forma: 'scatola',
      coloreSfondo: '#FFFFFF',
      coloreFascia: '#1E4FA0',
      coloreAccento: '#E2231A',
      scritta: 'Tachipirina',
      sottoscritta: '500 mg',
    },
    specifiche: {
      tipologia: 'Farmaco senza obbligo di ricetta',
      principioAttivo: 'Paracetamolo 500 mg',
      indicazioni:
        'Febbre, mal di testa, mal di denti e dolori lievi o moderati.',
      modoUso:
        'Segui dosi e intervalli indicati nel foglio illustrativo, senza superare la dose massima giornaliera.',
      avvertenze:
        'Non usarlo insieme ad altri medicinali che contengono paracetamolo. In caso di malattie del fegato chiedi prima al medico.',
    },
  },
  {
    id: 'p02',
    nome: 'Moment 200 mg',
    marca: 'Angelini',
    formato: '12 compresse rivestite',
    descrizione:
      'Ibuprofene contro mal di testa, mal di denti e dolori mestruali.',
    categoria: 'dolore-febbre',
    piuCercato: true,
    aspetto: {
      forma: 'scatola',
      coloreSfondo: '#FFFFFF',
      coloreFascia: '#C8102E',
      coloreAccento: '#F2A900',
      scritta: 'Moment',
      sottoscritta: '200 mg',
    },
    specifiche: {
      tipologia: 'Farmaco senza obbligo di ricetta',
      principioAttivo: 'Ibuprofene 200 mg',
      indicazioni:
        'Mal di testa, mal di denti, dolori mestruali, dolori muscolari e articolari.',
      modoUso:
        'Da assumere preferibilmente a stomaco pieno, secondo le indicazioni del foglio illustrativo.',
      avvertenze:
        'Non usarlo in caso di ulcera o di allergia ai farmaci antinfiammatori (FANS). In gravidanza chiedi prima al medico.',
    },
  },
  {
    id: 'p03',
    nome: 'OKi 80 mg',
    marca: 'Dompé',
    formato: '20 bustine',
    descrizione:
      'Ketoprofene sale di lisina in bustine, per dolori di varia natura e mal di gola.',
    categoria: 'dolore-febbre',
    piuCercato: false,
  },
  {
    id: 'p04',
    nome: 'Voltaren Emulgel 1%',
    marca: 'GSK',
    formato: 'tubo 60 g',
    descrizione:
      'Gel al diclofenac per dolori muscolari, contusioni e distorsioni.',
    categoria: 'dolore-febbre',
    piuCercato: false,
    aspetto: {
      forma: 'tubo',
      coloreSfondo: '#FFFFFF',
      coloreFascia: '#0B2D71',
      coloreAccento: '#E4002B',
      scritta: 'Voltaren',
      sottoscritta: 'Emulgel 1%',
    },
    specifiche: {
      tipologia: 'Farmaco senza obbligo di ricetta',
      principioAttivo: 'Diclofenac 1%',
      indicazioni:
        'Dolori muscolari e articolari, contusioni, distorsioni e piccoli traumi.',
      modoUso:
        'Applica uno strato sottile sulla zona dolorante massaggiando leggermente, poi lavati le mani.',
      avvertenze:
        'Solo per uso esterno. Non applicarlo su pelle ferita o irritata e non esporre al sole la zona trattata.',
    },
  },
  {
    id: 'p05',
    nome: 'Vicks Sinex Aloe',
    marca: 'Vicks',
    formato: 'spray nasale 15 ml',
    descrizione: 'Spray decongestionante che libera il naso chiuso.',
    categoria: 'raffreddore',
    piuCercato: false,
  },
  {
    id: 'p06',
    nome: 'Neoborocillina Gola',
    marca: 'Alfasigma',
    formato: '16 pastiglie',
    descrizione: 'Pastiglie da sciogliere in bocca per il mal di gola.',
    categoria: 'raffreddore',
    piuCercato: true,
  },
  {
    id: 'p07',
    nome: 'Fluimucil 600 mg',
    marca: 'Zambon',
    formato: '10 compresse effervescenti',
    descrizione: 'Acetilcisteina che rende il catarro più fluido da eliminare.',
    categoria: 'raffreddore',
    piuCercato: false,
  },
  {
    id: 'p08',
    nome: 'Tachifludec',
    marca: 'Angelini',
    formato: '12 bustine',
    descrizione:
      'Bustine da sciogliere in acqua calda contro i sintomi di raffreddore e influenza.',
    categoria: 'raffreddore',
    piuCercato: true,
  },
  {
    id: 'p09',
    nome: 'Gaviscon Advance',
    marca: 'Reckitt',
    formato: '12 bustine',
    descrizione: 'Contro il bruciore di stomaco e il reflusso dopo i pasti.',
    categoria: 'digestione',
    piuCercato: false,
  },
  {
    id: 'p10',
    nome: 'Enterogermina 2 miliardi',
    marca: 'Sanofi',
    formato: '10 flaconcini',
    descrizione: 'Fermenti lattici per riequilibrare la flora intestinale.',
    categoria: 'digestione',
    piuCercato: true,
    aspetto: {
      forma: 'flacone',
      coloreSfondo: '#FFFFFF',
      coloreFascia: '#0093D0',
      coloreAccento: '#FFD100',
      scritta: 'Enterogermina',
      sottoscritta: '2 miliardi',
    },
    specifiche: {
      tipologia: 'Farmaco senza obbligo di ricetta',
      principioAttivo: 'Spore di Bacillus clausii (2 miliardi)',
      indicazioni:
        'Riequilibrio della flora intestinale, ad esempio durante o dopo una cura antibiotica.',
      modoUso:
        'Agita il flaconcino e bevine il contenuto, puro o diluito in poca acqua.',
      avvertenze:
        "Se stai prendendo un antibiotico, assumilo a distanza di qualche ora dall'antibiotico.",
    },
  },
  {
    id: 'p11',
    nome: 'Buscopan 10 mg',
    marca: 'Sanofi',
    formato: '30 compresse',
    descrizione: 'Contro i dolori di pancia di tipo crampiforme.',
    categoria: 'digestione',
    piuCercato: false,
  },
  {
    id: 'p12',
    nome: 'Citrosodina Effervescente',
    marca: 'Montefarmaco',
    formato: '20 compresse',
    descrizione: 'Digestivo effervescente al bicarbonato per la cattiva digestione.',
    categoria: 'digestione',
    piuCercato: false,
  },
  {
    id: 'p13',
    nome: 'Bepanthenol Crema',
    marca: 'Bayer',
    formato: 'tubo 100 g',
    descrizione:
      'Crema alla provitamina B5 che aiuta la pelle irritata a rigenerarsi.',
    categoria: 'pelle-solari',
    piuCercato: true,
    aspetto: {
      forma: 'tubo',
      coloreSfondo: '#FFFFFF',
      coloreFascia: '#00857C',
      coloreAccento: '#8CC63F',
      scritta: 'Bepanthenol',
      sottoscritta: 'crema',
    },
    specifiche: {
      tipologia: 'Cosmetico',
      principioAttivo: 'Dexpantenolo (provitamina B5) 5%',
      indicazioni: 'Pelle secca, arrossata o irritata, anche delicata.',
      modoUso:
        'Applica una o più volte al giorno sulla pelle pulita e massaggia fino ad assorbimento.',
      avvertenze: 'Solo per uso esterno. Evita il contatto con gli occhi.',
    },
  },
  {
    id: 'p14',
    nome: 'Anthelios SPF 50+',
    marca: 'La Roche-Posay',
    formato: 'latte solare 100 ml',
    descrizione: 'Protezione solare molto alta per viso e corpo.',
    categoria: 'pelle-solari',
    piuCercato: false,
  },
  {
    id: 'p15',
    nome: 'Cicaplast Baume B5',
    marca: 'La Roche-Posay',
    formato: 'tubo 40 ml',
    descrizione: 'Balsamo lenitivo per pelle screpolata di viso, mani e labbra.',
    categoria: 'pelle-solari',
    piuCercato: false,
  },
  {
    id: 'p16',
    nome: 'Doposole idratante',
    marca: 'Avène',
    formato: 'flacone 200 ml',
    descrizione: 'Latte doposole che rinfresca e idrata la pelle dopo il mare.',
    categoria: 'pelle-solari',
    piuCercato: false,
  },
  {
    id: 'p17',
    nome: 'Supradyn Ricarica',
    marca: 'Bayer',
    formato: '30 compresse effervescenti',
    descrizione:
      'Integratore multivitaminico con sali minerali, utile nei periodi di stanchezza.',
    categoria: 'integratori',
    piuCercato: true,
    aspetto: {
      forma: 'cilindro',
      coloreSfondo: '#F28C00',
      coloreFascia: '#C8102E',
      coloreAccento: '#FFFFFF',
      scritta: 'Supradyn',
      sottoscritta: 'Ricarica',
    },
    specifiche: {
      tipologia: 'Integratore alimentare',
      principioAttivo: 'Vitamine del gruppo B, vitamina C, magnesio, ferro e zinco',
      indicazioni:
        'Integrazione di vitamine e minerali in caso di stanchezza o carenze nella dieta.',
      modoUso:
        "Sciogli una compressa in un bicchiere d'acqua, una volta al giorno.",
      avvertenze:
        'Non superare la dose giornaliera. Gli integratori non sostituiscono una dieta varia ed equilibrata.',
    },
  },
  {
    id: 'p18',
    nome: 'Magnesio Supremo',
    marca: 'Natural Point',
    formato: 'barattolo 150 g',
    descrizione: 'Magnesio in polvere da sciogliere in acqua, utile contro i crampi.',
    categoria: 'integratori',
    piuCercato: false,
  },
  {
    id: 'p19',
    nome: 'Vitamina D3 gocce',
    marca: 'Named',
    formato: 'flacone 10 ml',
    descrizione: 'Integratore di vitamina D per ossa e difese immunitarie.',
    categoria: 'integratori',
    piuCercato: false,
  },
  {
    id: 'p20',
    nome: 'Omega 3 RX',
    marca: 'Enerzona',
    formato: '48 capsule',
    descrizione: 'Capsule di olio di pesce a sostegno di cuore e colesterolo.',
    categoria: 'integratori',
    piuCercato: false,
  },
  {
    id: 'p21',
    nome: 'Amuchina Gel X-Germ',
    marca: 'Amuchina',
    formato: 'flacone 80 ml',
    descrizione: 'Gel disinfettante per le mani, senza bisogno di acqua.',
    categoria: 'igiene',
    piuCercato: false,
  },
  {
    id: 'p22',
    nome: 'Meridol Dentifricio',
    marca: 'Meridol',
    formato: 'tubo 75 ml',
    descrizione: 'Dentifricio per gengive che si infiammano e sanguinano.',
    categoria: 'igiene',
    piuCercato: false,
  },
  {
    id: 'p23',
    nome: 'Curasept Collutorio 0,12%',
    marca: 'Curasept',
    formato: 'flacone 200 ml',
    descrizione: 'Collutorio alla clorexidina per l’igiene della bocca.',
    categoria: 'igiene',
    piuCercato: false,
  },
  {
    id: 'p24',
    nome: 'Salviette detergenti',
    marca: 'Chicco',
    formato: '72 salviette',
    descrizione: 'Salviette delicate per la pulizia quotidiana dei bambini.',
    categoria: 'igiene',
    piuCercato: false,
  },
];

export default prodotti;
